version: '3.9'

services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://acp_user:86XodTYv77ynu01ib@108.181.199.102/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'DVGx8RkQOVvJxXqzb8C2C6EOQoj3pmq-R0oggHQEcDM='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'mysecret'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/www/acp/backend/acploads:/opt/acploads
    ports:
      - "8080:8080"
    command: webserver --debug

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://acp_user:86XodTYv77ynu01ib@108.181.199.102/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: 'mysecret'
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/www/acp/backend/acploads:/opt/acploads
    command: scheduler

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: airflow db init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://acp_user:86XodTYv77ynu01ib@108.181.199.102/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/www/acp/backend/acploads:/opt/acploads
